services:
  schema-registry:
    image: apicurio/apicurio-registry:3.0.9
    ports:
      - "8080:8080"

  shard1:
    image: postgres:17
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=5"
      - "-c"
      - "max_replication_slots=5"

  shard2:
    image: postgres:17
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=5"
      - "-c"
      - "max_replication_slots=5"

  liquibase1:
    image: liquibase/liquibase:4.32
    depends_on:
      - shard1
    command:
      - update
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.sql
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://shard1:5432/postgres
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgres
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: public
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    volumes:
      - "./liquibase/pg:/liquibase/changelog"

  liquibase2:
    image: liquibase/liquibase:4.32
    depends_on:
      - shard2
    command:
      - update
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.sql
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://shard2:5432/postgres
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgres
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: public
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    volumes:
      - "./liquibase/pg:/liquibase/changelog"