apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-config
data:
  additional-application.properties: |
    schema-registry.url=http://localhost:8080/apis/ccompat/v7
    schema-registry.compatibility=BACKWARD
    schema-registry.auto-register=true
    debezium.offset-storage.additional-properties."jdbc.table.ddl"=CREATE TABLE IF NOT EXISTS %s (id TEXT PRIMARY KEY, offset_key TEXT, offset_val TEXT, record_insert_ts TIMESTAMP NOT NULL, record_insert_seq INTEGER NOT NULL)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-engine-deployment
  labels:
    app: debezium-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-engine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: debezium-engine
    spec:
      containers:
        - name: debezium-engine
          image: debezium-poc:0.1.0
          env:
            - name: DEBEZIUM_APPLICATION_NAME
              value: "debezium-postgres-cdc-poc"
            - name: DEBEZIUM_MAX_BATCH_SIZE
              value: "1000"
            - name: DEBEZIUM_MAX_QUEUE_SIZE
              value: "4000"
            - name: DEBEZIUM_POLL_INTERVAL
              value: "500"
            - name: DEBEZIUM_SNAPSHOT_FETCH_SIZE
              value: "1000"
            - name: DEBEZIUM_OFFSET_STORAGE_TABLE_NAME
              value: "data.debezium_offsets"
            - name: DEBEZIUM_OFFSET_STORAGE_URL
              value: "jdbc:postgresql://postgres-cdc-environment:5432/zalando"
            - name: DEBEZIUM_OFFSET_STORAGE_USER
              valueFrom:
                secretKeyRef:
                  name: owner.postgres-cdc-environment.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DEBEZIUM_OFFSET_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owner.postgres-cdc-environment.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DEBEZIUM_DB_HOST
              value: "postgres-cdc-environment"
            - name: DEBEZIUM_DB_NAME
              value: "zalando"
            - name: DEBEZIUM_DB_PORT
              value: "5432"
            - name: DEBEZIUM_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: debezium.postgres-cdc-environment.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DEBEZIUM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: debezium.postgres-cdc-environment.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DEBEZIUM_TABLES
              value: "data.first,data.second,data.third"
            - name: DEBEZIUM_PUBLICATION_NAME
              value: "debezium_publication"
            - name: DEBEZIUM_SLOT_NAME
              value: "debezium_slot"
            - name: DEBEZIUM_TOPIC_PREFIX
              value: "debezium_topic_prefix"
            - name: DEBEZIUM_SNAPSHOT_MODE
              value: "INITIAL"
            - name: DEBEZIUM_EVENT_FORMAT
              value: "JSON"
            - name: S3_ENDPOINT
              value: "http://minio-service:9000"
            - name: S3_REGION
              value: "none"
            - name: S3_ACCESS_KEY
              value: "minioadmin"
            - name: S3_SECRET_ACCESS_KEY
              value: "minioadmin"
            - name: EVENT_SAVER_THRESHOLD_TIMEOUT
              value: "5m"
            - name: EVENT_SAVER_THRESHOLD_TOTAL_RECORDS
              value: "10"
            - name: QUARKUS_CONFIG_LOCATIONS
              value: "/quarkus/config/additional-application.properties"
            - name: JVM_OPTS
              value: "-Djava.security.manager=allow --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/sun.security.util=ALL-UNNAMED --add-opens java.base/sun.security.action=ALL-UNNAMED"
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          volumeMounts:
            - name: config-volume
              mountPath: "/quarkus/config"
      volumes:
        - name: config-volume
          configMap:
            name: quarkus-config