apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Release.Name }}
spec:
  dockerImage: ghcr.io/zalando/spilo-17:4.0-p2
  teamId: "local"
  numberOfInstances: 3
  users:  # Application/Robot users
    zalando:
      - superuser
      - createdb
    owner:
      - superuser
      - createdb
  # debezium user with replication role
    debezium:
      - replication
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  enableConnectionPooler: false # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service
  enableMasterPoolerLoadBalancer: false
  enableReplicaPoolerLoadBalancer: false
  allowedSourceRanges:  # load balancers' source ranges for both master and replica services
    - 127.0.0.1/32
  # databases: name->owner
  databases:
    zalando: owner
  preparedDatabases:
    zalando:
      defaultUsers: true
      extensions: {}
      schemas: {}
  postgresql:
    version: "17"
    parameters:
      shared_buffers: "128MB"
      max_connections: "10"
      log_statement: "all"
      wal_level: "logical"

  volume:
    size: 1Gi
  additionalVolumes:
    - name: empty
      mountPath: /opt/empty
      targetContainers:
        - all
      volumeSource:
        emptyDir: {}

  enableShmVolume: true
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
  patroni:
    failsafe_mode: false
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
      - local   all             all                                   trust
      - host    all             pgwatch2                127.0.0.1/32       trust
      - hostssl all             +zalandos    127.0.0.1/32       pam
      - host    all             all                127.0.0.1/32       md5
      - hostssl all             +zalandos    ::1/128            pam
      - host    all             all                ::1/128            md5
      - local   replication     standby                    trust
      - hostssl replication     standby all                md5
      - hostssl template1       pooler    all   reject
      - hostnossl all           all                all                md5
      - hostssl all             +zalandos    all                pam
      - hostssl all             all                all                md5
    slots: # ADD PERMANENT LOGICAL REPLICATION SLOT
      debezium_slot:
        type: logical
        database: zalando
        plugin: pgoutput
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    maximum_lag_on_failover: 33554432

  initContainers:
    - name: date
      image: busybox
      command: [ "/bin/date" ]

  tls:
    secretName: ""
    certificateFile: "tls.crt"
    privateKeyFile: "tls.key"
    caFile: ""
    caSecretName: ""
